### ISSUE TITLE
Being compliant with the official test suite?

### ISSUE THREAD

**Issue by dahlia** [disjukr/bencodex#1]
Thanks for writing the first JavaScript implementation of Bencodex.

The Bencodex specification repository provides a [set of encoding–semantics pairs][1] to testify an implementation's accuracy.  It would be great if this implementation is tested with them.

Is there something I might help you?  I could show you some patches for that if you give me some hint (e.g., a testing framework of your preference to use).

[1]: https://github.com/planetarium/bencodex/tree/1.0#test-suite

**Comment by disjukr** [comment]
https://github.com/disjukr/bencodex/blob/master/test/test.ts
